#!/usr/bin/env php
<?php
/**
 * Writes supervisord program blocks for each entry in get_servers() (max 5).
 * Run at container start before supervisord.
 */

require '/var/www/html/config.inc.php';

$outPath = getenv('SUPERVISOR_DAEMONS_CONF') ?: '/etc/supervisor/conf.d/fan-daemons.generated.conf';
$autoDaemon = filter_var(getenv('AUTO_DAEMON') ?: 'true', FILTER_VALIDATE_BOOLEAN);

$lines = [
    '; Auto-generated by docker/generate-supervisor-daemons.php — do not edit',
    '',
];

if ($autoDaemon) {
    $servers = array_slice(get_servers(), 0, 5);
    foreach ($servers as $s) {
        $id = isset($s['id']) ? (string) $s['id'] : '';
        if ($id === '') {
            continue;
        }
        $prog = preg_replace('/[^a-zA-Z0-9_-]/', '_', $id);
        if ($prog === '') {
            $prog = 'server';
        }
        $arg = escapeshellarg($id);
        $lines[] = "[program:fan-daemon-{$prog}]";
        $lines[] = "command=php /var/www/html/fan-daemon.php {$arg}";
        $lines[] = 'autostart=true';
        $lines[] = 'autorestart=unexpected';
        $lines[] = 'stdout_logfile=/dev/stdout';
        $lines[] = 'stdout_logfile_maxbytes=0';
        $lines[] = 'stderr_logfile=/dev/stderr';
        $lines[] = 'stderr_logfile_maxbytes=0';
        $lines[] = 'user=www-data';
        $lines[] = '';
    }
}

$content = implode("\n", $lines);
if (!str_ends_with($content, "\n")) {
    $content .= "\n";
}

if (file_put_contents($outPath, $content) === false) {
    fwrite(STDERR, "Failed to write {$outPath}\n");
    exit(1);
}
