[supervisord]
nodaemon=true
logfile=/var/log/supervisor/supervisord.log
pidfile=/var/run/supervisord.pid

[program:apache2]
command=/usr/sbin/apache2ctl -D FOREGROUND
autostart=true
autorestart=true
stderr_logfile=/var/log/supervisor/apache2.err.log
stdout_logfile=/var/log/supervisor/apache2.out.log

[program:fan-daemon]
command=php /var/www/html/fan-daemon.php
autostart=true
autorestart=true
stderr_logfile=/var/log/supervisor/fan-daemon.err.log
stdout_logfile=/var/log/supervisor/fan-daemon.out.log
user=www-data
